# Generated by Django 5.2.4 on 2025-07-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('department', '0005_remove_section_current_semester_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_semester',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_profiles', to='department.semester'),
        ),
    ]
