# Generated by Django 5.2.4 on 2025-07-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_studentprofile_current_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='office_location',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
