# Generated by Django 5.2.4 on 2025-07-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('test', 'Test')], max_length=20),
        ),
    ]
