# Generated by Django 5.2.4 on 2025-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_code',
        ),
    ]
