# Generated by Django 5.2.4 on 2025-07-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_department_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_code',
        ),
    ]
