# Generated by Django 5.2.4 on 2025-07-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='current_semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
