# Generated by Django 5.2.4 on 2025-07-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_remove_section_current_semester_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='academic_year',
        ),
    ]
